# Generated by Django 3.2.1 on 2021-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosakata', '0002_kosakata_arti_kata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kosakata',
            name='arti_kata',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
