# Generated by Django 3.2.1 on 2021-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauji',
            name='cleaned_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
