# Generated by Django 3.2.1 on 2021-07-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uji', '0002_alter_datauji_cleaned_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauji',
            name='stemmed_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
